- id: 'xxxxxxxxxxxxxx'
  alias: P1toSmartevse
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /3
  condition: []
  action:
  - service: shell_command.dsmrtosmartevse
    data: {}
  mode: single
